# Linear Algebra
## Ch05 - Intro to Matrices

## Matrix terminology and dimensionality

Notation:

$$\large
A=\begin{bmatrix}
1 & 6 & 0\\
7 & 2 & 4\\
4 & 1 & 1
\end{bmatrix} \ \ \ \ \ \ \ \ \ \ a_{1,2} =6
$$

This is a $3\times 3$ Matrix. Where:
- $\mathbb{R}^{M\times N}$
- M = Rows
- N = Columns

Note: $\mathbb{R}^{M\times N}$ is **different** than $\mathbb{R}^{MN}$.

Dimensionality refers to the **number of elements** in the matrix.

In [2]:
import numpy as np

In [6]:
# Square vs. Rectangular
S = np.round(np.random.randn(5,5))
R = np.round(np.random.randn(5,2)) # 5 rows, 2 columns
print(f"Square:\n{S}"), print('')
print(f"Rectangular:\n{R}"), print('')

# Identity
I = np.eye(3)
print(f"Identity:\n{I}"), print('')

# Zeros
Z = np.zeros((4,4))
print(f"Zeros:\n{Z}"), print('')

# Diagonal
D = np.diag([ 1, 2, 3, 5, 2 ])
print(f"Diagonal:\n{D}"), print('')

# Create triangular matrix from full matrices
S = np.random.randn(5,5)
U = np.triu(S)
L = np.tril(S)
print(f"Triangular:\n{np.round(L)}"), print('')

# Concatenate matrices (sizes must match!)
A = np.random.randn(3,2)
B = np.random.randn(3,4)
C = np.concatenate((A,B),axis=1)
print(f"Concatenate A & B:\n{np.round(C)}")

Square:
[[-0. -0. -1. -2.  1.]
 [ 1. -1.  0.  0. -1.]
 [-0.  1.  1. -1.  1.]
 [-0. -1. -2. -0. -0.]
 [ 2. -0. -2.  1.  1.]]

Rectangular:
[[ 0. -1.]
 [ 1.  1.]
 [-0.  1.]
 [-0.  0.]
 [-0. -0.]]

Identity:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Diagonal:
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 5 0]
 [0 0 0 0 2]]

Triangular:
[[-1.  0.  0.  0.  0.]
 [-1. -1.  0.  0.  0.]
 [-1. -1. -1.  0.  0.]
 [-0.  1.  2. -1.  0.]
 [-2.  0.  0.  1. -2.]]

Concatenate A & B:
[[-3. -2. -0.  1.  0. -0.]
 [ 0.  0. -0.  0. -0. -1.]
 [ 0.  1.  2.  2.  1.  1.]]
