#     COURSE: Linear algebra: theory and implementation
##    SECTION: Introduction to matrices

#### Instructor: sincxpress.com
##### Course url: https://www.udemy.com/course/linear-algebra-theory-and-implementation/?couponCode=202110

In [1]:
import numpy as np


---
# VIDEO: A zoo of matrices
---


In [2]:

# square vs. rectangular
S = np.random.randn(5,5)
R = np.random.randn(5,2) # 5 rows, 2 columns
print(S), print(' ')
print(R)

# identity
I = np.eye(3)
print(I), print(' ')

# zeros
Z = np.zeros((4,4))
print(Z), print(' ')

# diagonal
D = np.diag([ 1, 2, 3, 5, 2 ])
print(D), print(' ')

# create triangular matrix from full matrices
S = np.random.randn(5,5)
U = np.triu(S)
L = np.tril(S)
print(L), print(' ')

# concatenate matrices (sizes must match!)
A = np.random.randn(3,2)
B = np.random.randn(3,4)
C = np.concatenate((A,B),axis=1)
print(C)

[[ 0.40035178  0.81623166 -1.09567571  0.37174748 -1.65856456]
 [-0.41256075 -0.75580633 -0.78045796  0.84936441 -0.24116269]
 [ 2.06244762  0.88883463 -0.1306926  -0.9225125   0.96863571]
 [-0.67489899  0.57732944 -0.57635208 -0.36879772  0.80019757]
 [ 0.89368471  0.00769033  0.34544088 -1.2748597   0.15790392]]
 
[[-1.32362188 -1.75495522]
 [-1.61950665  0.41244045]
 [-1.08814878 -0.50297829]
 [ 1.09302434 -0.89341949]
 [-0.74360937 -0.08601154]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
 
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 5 0]
 [0 0 0 0 2]]
 
[[ 1.19114555  0.          0.          0.          0.        ]
 [ 0.01191078  0.38268653  0.          0.          0.        ]
 [-0.58475417 -0.53574214 -0.05493842  0.          0.        ]
 [-0.91798907  0.03391648 -0.66092711 -0.59902288  0.        ]
 [-0.62357738  0.22795121 -0.51048092  0.72139067  0.81568424]]
 
[[ 0.18153735 -0.5042987  -0.00957847 -0.73523023 -0.59805


---
# VIDEO: Matrix addition and subtraction
---


In [3]:

# create random matrices
A = np.random.randn(5,4)
B = np.random.randn(5,3)
C = np.random.randn(5,4)

# try to add them
# A+B
A+C



# "shifting" a matrix
l = .03 # lambda
N = 5  # size of square matrix
D = np.random.randn(N,N) # can only shift a square matrix

Ds = D + l*np.eye(N)
print(D), print(' '), print(Ds)

[[ 0.20574485 -0.88097208 -0.30078336  0.62236866  0.37174419]
 [ 0.31459866 -2.457807   -0.40848832  0.55222187  0.52277397]
 [ 1.33938397  0.04145486  0.71555417 -0.11538444 -1.62207068]
 [ 1.04424481 -0.12318707  1.3665267   0.43079977  1.52676914]
 [ 0.71532939 -0.19449427  2.44019614  0.59916925 -0.75824199]]
 
[[ 0.23574485 -0.88097208 -0.30078336  0.62236866  0.37174419]
 [ 0.31459866 -2.427807   -0.40848832  0.55222187  0.52277397]
 [ 1.33938397  0.04145486  0.74555417 -0.11538444 -1.62207068]
 [ 1.04424481 -0.12318707  1.3665267   0.46079977  1.52676914]
 [ 0.71532939 -0.19449427  2.44019614  0.59916925 -0.72824199]]


(None, None, None)


---
# VIDEO: Matrix-scalar multiplication
---


In [4]:
# define matrix and scalar
M = np.array([ [1, 2], [2, 5] ])
s = 2

# pre- and post-multiplication is the same:
print( M*s )
print( s*M )


[[ 2  4]
 [ 4 10]]
[[ 2  4]
 [ 4 10]]


# VIDEO: Transpose

In [5]:
M = np.array([ [1,2,3],
               [2,3,4] ])

print(M), print('')
print(M.T), print('') # one transpose
print(M.T.T), print('') # double-transpose returns the original matrix

# can also use the function transpose
print(np.transpose(M))

[[1 2 3]
 [2 3 4]]

[[1 2]
 [2 3]
 [3 4]]

[[1 2 3]
 [2 3 4]]

[[1 2]
 [2 3]
 [3 4]]


In [6]:
# warning! be careful when using complex matrices
C = np.array([ [4+1j , 3 , 2-4j] ])

print(C), print('')
print(C.T), print('')
print(np.transpose(C)), print('')

# Note: In MATLAB, the transpose is the Hermitian transpose; 
#       in Python, you need to call the Hermitian explicitly by first converting from an array into a matrix
print(np.matrix(C).H) # note the sign flips!


[[4.+1.j 3.+0.j 2.-4.j]]

[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]

[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]

[[4.-1.j]
 [3.-0.j]
 [2.+4.j]]



---
# VIDEO: Diagonal and trace
---


In [7]:

M = np.round( 6*np.random.randn(4,4) )
print(M), print(' ')
# extract the diagonals
d = np.diag(M)

# notice the two ways of using the diag function
d = np.diag(M) # input is matrix, output is vector
D = np.diag(d) # input is vector, output is matrix
print(d)
print(D)

# trace as sum of diagonal elements
tr = np.trace(M)
tr2 = sum( np.diag(M) )
print(tr,tr2)

[[-3. -1. -6. -5.]
 [ 6. -9.  0.  6.]
 [ 2. -3. -2.  4.]
 [ 3. -9.  0. -5.]]
 
[-3. -9. -2. -5.]
[[-3.  0.  0.  0.]
 [ 0. -9.  0.  0.]
 [ 0.  0. -2.  0.]
 [ 0.  0.  0. -5.]]
-19.0 -19.0



---
# VIDEO: Broadcasting matrix arithmetic
---


In [8]:
# create a matrix
A = np.reshape(np.arange(1,13),(3,4),'F') # F=column, C=row

# and two vectors
r = [ 10, 20, 30, 40 ]
c = [ 100, 200, 300 ]

print(A), print(' ')
print(r), print(' ')
print(c), print(' ');

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
 
[10, 20, 30, 40]
 
[100, 200, 300]
 


In [9]:
# broadcast on the rows
# print(A+r), print(' ')

# broadcast on the columns
# print(A+c)
print(A+np.reshape(c,(len(c),1))) # only works for explicit column vectors


[[101 104 107 110]
 [202 205 208 211]
 [303 306 309 312]]
