#     COURSE: Linear algebra: theory and implementation
##    SECTION: Introduction to matrices

#### Instructor: sincxpress.com
##### Course url: https://www.udemy.com/course/linear-algebra-theory-and-implementation/?couponCode=202110

In [1]:
import numpy as np


---
# VIDEO: A zoo of matrices
---


In [2]:

# square vs. rectangular
S = np.random.randn(5,5)
R = np.random.randn(5,2) # 5 rows, 2 columns
print(S), print(' ')
print(R)

# identity
I = np.eye(3)
print(I), print(' ')

# zeros
Z = np.zeros((4,4))
print(Z), print(' ')

# diagonal
D = np.diag([ 1, 2, 3, 5, 2 ])
print(D), print(' ')

# create triangular matrix from full matrices
S = np.random.randn(5,5)
U = np.triu(S)
L = np.tril(S)
print(L), print(' ')

# concatenate matrices (sizes must match!)
A = np.random.randn(3,2)
B = np.random.randn(3,4)
C = np.concatenate((A,B),axis=1)
print(C)

[[-0.4992457   2.10707765 -0.04144208  0.14267418 -0.14314629]
 [-1.53823393 -0.66005929 -0.9224859  -0.53118322  1.03893233]
 [-0.4672792  -0.94144891 -0.35541174 -1.68066966 -0.57389174]
 [ 0.56847731  1.26573555 -0.02872613 -0.04390629  0.02108804]
 [-1.07586804 -0.6929481   0.24450567  0.56132055  0.8334327 ]]
 
[[ 0.31025161  0.33893275]
 [-1.38163097  0.43818471]
 [ 0.72204267  0.04374088]
 [ 0.52631054  0.6426914 ]
 [-0.62607933 -0.66748791]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
 
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 5 0]
 [0 0 0 0 2]]
 
[[-0.39880508  0.          0.          0.          0.        ]
 [ 0.64255389 -0.14006324  0.          0.          0.        ]
 [-0.51499118  0.83648653 -0.22222673  0.          0.        ]
 [-0.4968846   0.14200845 -0.81519529 -2.57901942  0.        ]
 [-1.72776836  0.5736127   0.4271688   0.232622    0.26969692]]
 
[[-0.49433     0.33325806  0.47237449  0.26300114  1.88386


---
# VIDEO: Matrix addition and subtraction
---


In [3]:

# create random matrices
A = np.random.randn(5,4)
B = np.random.randn(5,3)
C = np.random.randn(5,4)

# try to add them
# A+B
A+C



# "shifting" a matrix
l = .03 # lambda
N = 5  # size of square matrix
D = np.random.randn(N,N) # can only shift a square matrix

Ds = D + l*np.eye(N)
print(D), print(' '), print(Ds)

[[-0.40753867  0.52260048  1.75584473 -0.50159822 -1.00069371]
 [ 0.84560686 -0.6395312   0.78511149  0.18425179  0.10039568]
 [ 0.27366418 -0.31014789 -0.41836814 -0.15368163 -0.89617635]
 [ 0.290985    0.21695745  0.71029641 -0.59964882  0.25371206]
 [-0.67491565  0.47743932 -1.00990784  1.42920153  0.48428454]]
 
[[-0.37753867  0.52260048  1.75584473 -0.50159822 -1.00069371]
 [ 0.84560686 -0.6095312   0.78511149  0.18425179  0.10039568]
 [ 0.27366418 -0.31014789 -0.38836814 -0.15368163 -0.89617635]
 [ 0.290985    0.21695745  0.71029641 -0.56964882  0.25371206]
 [-0.67491565  0.47743932 -1.00990784  1.42920153  0.51428454]]


(None, None, None)


---
# VIDEO: Matrix-scalar multiplication
---


In [4]:
# define matrix and scalar
M = np.array([ [1, 2], [2, 5] ])
s = 2

# pre- and post-multiplication is the same:
print( M*s )
print( s*M )


[[ 2  4]
 [ 4 10]]
[[ 2  4]
 [ 4 10]]


# VIDEO: Transpose

In [5]:
M = np.array([ [1,2,3],
               [2,3,4] ])

print(M), print('')
print(M.T), print('') # one transpose
print(M.T.T), print('') # double-transpose returns the original matrix

# can also use the function transpose
print(np.transpose(M))

[[1 2 3]
 [2 3 4]]

[[1 2]
 [2 3]
 [3 4]]

[[1 2 3]
 [2 3 4]]

[[1 2]
 [2 3]
 [3 4]]


In [6]:
# warning! be careful when using complex matrices
C = np.array([ [4+1j , 3 , 2-4j] ])

print(C), print('')
print(C.T), print('')
print(np.transpose(C)), print('')

# Note: In MATLAB, the transpose is the Hermitian transpose; 
#       in Python, you need to call the Hermitian explicitly by first converting from an array into a matrix
print(np.matrix(C).H) # note the sign flips!


[[4.+1.j 3.+0.j 2.-4.j]]

[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]

[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]

[[4.-1.j]
 [3.-0.j]
 [2.+4.j]]



---
# VIDEO: Diagonal and trace
---


In [7]:

M = np.round( 6*np.random.randn(4,4) )
print(M), print(' ')
# extract the diagonals
d = np.diag(M)

# notice the two ways of using the diag function
d = np.diag(M) # input is matrix, output is vector
D = np.diag(d) # input is vector, output is matrix
print(d)
print(D)

# trace as sum of diagonal elements
tr = np.trace(M)
tr2 = sum( np.diag(M) )
print(tr,tr2)

[[ -4.   1.   1.  -2.]
 [ -1.   7.   5.  -2.]
 [  5.  -3.  -3.   5.]
 [-12.   8.  -4. -16.]]
 
[ -4.   7.  -3. -16.]
[[ -4.   0.   0.   0.]
 [  0.   7.   0.   0.]
 [  0.   0.  -3.   0.]
 [  0.   0.   0. -16.]]
-16.0 -16.0



---
# VIDEO: Broadcasting matrix arithmetic
---


In [8]:
# create a matrix
A = np.reshape(np.arange(1,13),(3,4),'F') # F=column, C=row

# and two vectors
r = [ 10, 20, 30, 40 ]
c = [ 100, 200, 300 ]

print(A), print(' ')
print(r), print(' ')
print(c), print(' ');

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
 
[10, 20, 30, 40]
 
[100, 200, 300]
 


In [9]:
# broadcast on the rows
# print(A+r), print(' ')

# broadcast on the columns
# print(A+c)
print(A+np.reshape(c,(len(c),1))) # only works for explicit column vectors


[[101 104 107 110]
 [202 205 208 211]
 [303 306 309 312]]
