# Linear Algebra
## Matrix Multiplication

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math

## "Standard" matrix multiplication
Matrix multiplication is NOT commutative, the order matters! $AB \neq BA$

Rules for matrix multiplication:
- The number of columns in the left matrix must be the same as the number of rows in the right matrix.
> Inner dimensions must match ($N, N$)
- The result will be a matrix with the same number of rows in the left matrix and the same number of columns in the right matrix.
> Outer dimensions is the size of resulting matrix ($M, K$)

$$\large
\begin{matrix}
\begin{bmatrix}
 &  &  &  &  & \\
 &  &  &  &  & \\
 &  &  &  &  & \\
 &  &  &  &  & 
\end{bmatrix} & \begin{bmatrix}
 & \\
 & \\
 & \\
 & \\
 & \\
 & 
\end{bmatrix} & = & \begin{bmatrix}
 & \\
 & \\
 & \\
 & 
\end{bmatrix}\\
M\times N & N\times K &  & M\times K
\end{matrix}
$$

### Element perspective matrix multiplication
Each element $c_{i,j}$ in $AB=C$ is the dot product between the $\text i^{th}$ row in $A$ and the $\text j^{th}$ column in $B$.

$$\large
\begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}\begin{bmatrix}
a & b\\
c & d
\end{bmatrix} =\begin{bmatrix}
1a+2c & 1b+2d\\
3a+4c & 3b+4d
\end{bmatrix}
$$

In [2]:
# Rules for multiplication validity
m = 4
n = 3
k = 6

# Make some matrices
A = np.round(np.random.randn(m,n)) # 4x3
B = np.round(np.random.randn(n,k)) # 3x6
C = np.round(np.random.randn(m,k)) # 4x6

# Test which multiplications are valid
# Think of your answer first, then test
print('A * B:')
print(np.matmul(A,B)), print() # yes

# np.matmul(A,A) # no

print('A.T * C:')
print(np.matmul(A.T,C)), print() # yes

print('B * B.T:')
print(np.matmul(B,B.T)), print() # yes

print('B.T * B:')
print(np.matmul(np.matrix.transpose(B),B)), print() # yes

# np.matmul(B,C) # no
# np.matmul(C,B) # no
# np.matmul(C.T,B) # no

print('C * B.T:')
print(np.matmul(C,B.T)) # yes

A * B:
[[ 0. -2.  0. -2. -2.  0.]
 [ 0.  2.  1.  0.  2.  0.]
 [ 0.  1.  0.  1.  1.  0.]
 [ 0.  1. -1.  2.  2.  0.]]

A.T * C:
[[ 2.  1. -7.  0. -4. -3.]
 [-1. -1.  4.  0.  3.  2.]
 [ 0.  2.  3.  4.  2.  1.]]

B * B.T:
[[5. 4. 3.]
 [4. 5. 2.]
 [3. 2. 3.]]

B.T * B:
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  2.  0.  1.  3.  0.]
 [ 0.  0.  1.  0. -2.  0.]
 [ 0.  1.  0.  1.  1.  0.]
 [ 0.  3. -2.  1.  9.  0.]
 [ 0.  0.  0.  0.  0.  0.]]

C * B.T:
[[-1.  1. -3.]
 [-2.  1. -1.]
 [-2. -3.  0.]
 [ 3.  3.  1.]]


## Code challenge: matrix multiplication by layering
Implement matrix multiplication via layers.

1. Generate two matrices (A, B)
2. Build the product matrix layer-wise (for loops)
3. Implement the matrix multiplication directly (multiplying two matrices without a loop)
4. Compare results

In [3]:
# 1. Define matrices A & B
m = 4
n = 3
A = np.round(np.random.randn(m, n), 2)
B = np.round(np.random.randn(n, m), 2)
print(A), print()
print(B), print()


# 2. Build the product matrix layer-wise (for loops)
matrix = np.zeros((m, m))
for i in range(m):
    for j in range(m):
        # matrix[i][j] = np.dot(A[i], B[:,j])
        matrix[i][j] = np.sum(A[i] * B[:,j])
        
# 3. Implement the matrix multiplication directly (multiplying two matrices without a loop)
np_mult = np.matmul(A, B)

# Compare results
print(f"Layer-wise matrix: \n{np.round(matrix, 3)}\n")
print(f"NumPy direct multiplication: \n{np.round(np_mult, 3)}")

[[-0.71  0.17 -0.77]
 [ 0.82 -1.06 -3.08]
 [-0.21  0.26  1.58]
 [-0.09 -0.02  0.68]]

[[ 0.44 -0.76 -0.5   0.83]
 [ 1.71  0.86 -0.96 -0.15]
 [-0.67 -0.7   0.52  0.63]]

Layer-wise matrix: 
[[ 0.494  1.225 -0.209 -1.1  ]
 [ 0.612  0.621 -0.994 -1.101]
 [-0.706 -0.723  0.677  0.782]
 [-0.529 -0.425  0.418  0.357]]

NumPy direct multiplication: 
[[ 0.494  1.225 -0.209 -1.1  ]
 [ 0.612  0.621 -0.994 -1.101]
 [-0.706 -0.723  0.677  0.782]
 [-0.529 -0.425  0.418  0.357]]
