# Linear Algebra
## Ch03 - Vector Multiplication

## Dot product

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from mpl_toolkits.mplot3d import Axes3D

In [2]:
# dot product
v1 = np.array([2, 5, 4, 7])
v2 = np.array([4, 1, 0, 2])
np.dot(v1, v2)

27

In [3]:
v3 = v1*v2
v3

array([ 8,  5,  0, 14])

### Distributive property of dot product

$$\large
w^{T}( u+v) \ =\ w^{T} u\ +\ w^{T} v
$$

The dot product is defined as the sum of element-wise multiplications. Common terms can be combined across sums, which brings us to the following:

$$\large
\sum _{i=1}^{n} w_{i}( u_{i} +v_{i}) \ =\ \sum _{i=1}^{n} w_{i} u_{i} \ +\ \sum _{i=1}^{n} w_{i} v_{i}
$$


In [4]:
u = np.array([1, 2])
v = np.array([1, 3])
w = np.array([2, 3])

# Distributive property of dot product
print(np.dot(w.T, (u+v)))
print(np.dot(w.T, u) + np.dot(w.T, v))

19
19


Example of applying the distributive property of the dot product between a vector and itself:

$$\large
( u+v)^{T}( u+v) \ =\ \| u+v\| ^{2} \ =\ u^{T} u\ +\ 2u^{T} v\ +\ v^{T} v\ =\ \| u\| ^{2} \ +\ \| v\| ^{2} \ +\ 2u^{T} v
$$

In [5]:
# Distributive property to the dot product between a vector and itself
np.dot((u+v).T, (u+v))

29

### Linear weighted combination

It's a scalar-vector multiplication and addition.

$$\large
w = \lambda _{1} v_{1} + \lambda _{2} v_{2} + \lambda _{3} v_{3} + ... + \lambda _{n} v_{n}
$$

In [6]:
# Define scalars and vectors
l1 = 1
l2 = 2
l3 = -3
v1 = np.array([4, 5, 1])
v2 = np.array([-4, 0, -4])
v3 = np.array([1, 3, 2])

# Linear weighted combination
l1*v1 + l2*v2 + l3*v3

array([ -7,  -4, -13])

## Outer product
Combining two vectors to produce a matrix. The two vectors don't need to have the same size. The result is a $M\times N$ matrix.

**Dot product:**

$\large v^{T}w = 1\times 1$


**Outer product:**

$\large vw^{T} = M\times N$

This notation indicates that the dot product $(v^{T}w)$ is a $1\times 1$ array (just a single number; a scalar) whereas the outer product $(vw^{T})$ is a matrix whose sizes are defined by the number of elements in the vectors.

### The outer product formula
$$\large
(vw^T)_{ij} = v_i w_j
$$

Example:

$$\large
\begin{bmatrix}
a\\
b\\
c
\end{bmatrix}\begin{bmatrix}
d & e & f
\end{bmatrix} =\begin{bmatrix}
ad & ae & af\\
bd & be & bf\\
cd & ce & cf
\end{bmatrix}
$$

In [7]:
# Define vectors
v = np.array([2, 5, 4, 7])
w = np.array([4, 1, 0, 2])

# Dot vs Outer product
dot = np.dot(v, w)
out = np.outer(v, w)

print(f"Dot product: {dot}\n")
print(f"Outer product: \n{out}")

Dot product: 27

Outer product: 
[[ 8  2  0  4]
 [20  5  0 10]
 [16  4  0  8]
 [28  7  0 14]]


In [8]:
# Vectors with different dimensions M*N
v = np.array([1, 2, 3, 4])
w = np.array([4, 1, -1])

# Outer product
np.outer(v, w)

array([[ 4,  1, -1],
       [ 8,  2, -2],
       [12,  3, -3],
       [16,  4, -4]])

In [9]:
a = np.array([3, 40])
b = np.array([10, 2, 30, 4])
c = np.outer(a, b)
c

array([[  30,    6,   90,   12],
       [ 400,   80, 1200,  160]])

## Element-wise product
Multiplying each corresponding element in two vectors. Both vectors must have the same size. This operation results in another vector of the same size $M\times N$

$$\large
c=a\odot b=[ a_{1} b_{1} \ \ \ a_{2} b_{2} \ \ \ ...\ \ \ a_{n} b_{n}]
$$



In [10]:
# Two vectors with the same size
a = np.array([2, 5, 4, 7])
b = np.array([4, 1, 0, 2])

# Element-wise product
c = a * b
c

array([ 8,  5,  0, 14])

## Cross product
Defined only for 3-element vectors. Result is another 3-element vector.

$$\large
a\times b=\begin{bmatrix}
a_{2} b_{3}{} & a_{3} b_{2}\\
a_{3} b_{1} & a_{1} b_{3}\\
a_{1} b_{2} & a_{2} b_{1}
\end{bmatrix}
$$

In [11]:
# Two vectors with same size
a = np.array([5, 3, 4])
b = np.array([-2, 1, -1])

# Cross product
c = np.cross(a, b)
c

array([-7, -3, 11])

## Unit vectors
Have magnitude of one: $\| v\| =1$

Unit vectors allow the creation of orthogonal matrix.

$\large
\mu v\ \ \operatorname{s.t.} \ \ \| \mu v\| =1\ \ \ \operatorname{( s.t.\ means\ "such\ that"\ or\ "subject\ to")}
$

$\mu$ is a scalar used to compute a unit vector in the same direction as vector $v$.

### Creating a unit-lenght vector
Set $\mu$ to be the reciprocal (inverse) of the magnitude of the vector. In notation, a unit vector is given a hat to indicate it has a magnitude of one ($v\rightarrow \hat{v}$)

$$\large
\hat{v} =\frac{1}{\| v\| } v=\frac{1}{\sqrt{\sum _{i=1}^{n} v_{i}^{2}}} v
$$

The norm of the vector, $\| v\|$, is a scalar, which means:
1. Division is allowed (division by a full vector is not defined)
2. ___Direction of the vector does not change___

Example:

$$\large
v=\begin{bmatrix}
0\\
2
\end{bmatrix} ,\ \ \ \ \ \ \ \hat{v} =\frac{1}{\sqrt{0^{2} +2^{2}}}\begin{bmatrix}
0\\
2
\end{bmatrix} =\begin{bmatrix}
0\\
1
\end{bmatrix}
$$

Taking $\mu = \frac{1}{\| v\|}\| v\| = 1$ allows for a quick proof tha the unit vector really does have unit lenght:

$$\large
\| \mu v\| = \frac{1}{\| v\|}\| v\| = 1
$$

In [12]:
# Vector
v = np.array([0, 2])

# Magnitude
vMag = np.linalg.norm(v)

# Unit vector
v_unit = v/vMag
v_unit

array([0., 1.])

In [13]:
# Unit vector computation
v = np.array([2, 5, 4, 7])
vMag = np.linalg.norm(v)
v_unit = v/vMag
v_unit

array([0.20628425, 0.51571062, 0.4125685 , 0.72199487])

In [14]:
# Unit vector computation
v = np.array([3, 4])
vMag = np.linalg.norm(v)
v_unit = v/vMag
v_unit

array([0.6, 0.8])